-- =================================================================
-- MODÈLE DE DONNÉES RETAIL POUR DÉMONSTRATION SNOWFLAKE
-- =================================================================

-- Table des Catégories de Produits
CREATE TABLE CATEGORIES (
    CATEGORY_ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PARENT_CATEGORY_ID INT,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Table des Produits
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    CATEGORY_ID INT NOT NULL,
    BRAND VARCHAR(100),
    PRICE DECIMAL(10,2) NOT NULL,
    COST DECIMAL(10,2) NOT NULL,
    STOCK_QUANTITY INT DEFAULT 0,
    SUPPLIER VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
);

-- Table des Magasins
CREATE TABLE STORES (
    STORE_ID INT PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    ADDRESS VARCHAR(300),
    CITY VARCHAR(100) NOT NULL,
    REGION VARCHAR(100),
    COUNTRY VARCHAR(100) NOT NULL,
    POSTAL_CODE VARCHAR(20),
    MANAGER_NAME VARCHAR(100),
    OPENING_DATE DATE,
    STORE_TYPE VARCHAR(50), -- 'Flagship', 'Standard', 'Outlet'
    SURFACE_M2 INT,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Table des Clients  
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(300),
    CITY VARCHAR(100),
    REGION VARCHAR(100),
    COUNTRY VARCHAR(100) NOT NULL,
    POSTAL_CODE VARCHAR(20),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(10),
    CUSTOMER_SEGMENT VARCHAR(50), -- 'Premium', 'Standard', 'Bronze'
    REGISTRATION_DATE DATE NOT NULL,
    LAST_LOGIN_DATE TIMESTAMP,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Table des Commandes
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    STORE_ID INT NOT NULL,
    ORDER_DATE TIMESTAMP NOT NULL,
    STATUS VARCHAR(50) NOT NULL, -- 'Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled'
    TOTAL_AMOUNT DECIMAL(12,2) NOT NULL,
    DISCOUNT_AMOUNT DECIMAL(10,2) DEFAULT 0,
    TAX_AMOUNT DECIMAL(10,2) DEFAULT 0,
    PAYMENT_METHOD VARCHAR(50), -- 'Credit Card', 'Debit Card', 'Cash', 'PayPal'
    SHIPPING_ADDRESS TEXT,
    DELIVERY_DATE TIMESTAMP,
    NOTES TEXT,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID)
);

-- Table des Lignes de Commande
CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID INT PRIMARY KEY,
    ORDER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    DISCOUNT_PERCENT DECIMAL(5,2) DEFAULT 0,
    LINE_TOTAL DECIMAL(12,2) AS (QUANTITY * UNIT_PRICE * (1 - DISCOUNT_PERCENT/100)),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- =================================================================
-- VUES POUR L'ANALYSE ET LES AGRÉGATIONS
-- =================================================================

-- Vue : Résumé des ventes par produit
CREATE VIEW V_PRODUCT_SALES AS
SELECT 
    p.PRODUCT_ID,
    p.NAME as PRODUCT_NAME,
    c.NAME as CATEGORY_NAME,
    p.BRAND,
    COUNT(DISTINCT oi.ORDER_ID) as TOTAL_ORDERS,
    SUM(oi.QUANTITY) as TOTAL_QUANTITY_SOLD,
    SUM(oi.LINE_TOTAL) as TOTAL_REVENUE,
    AVG(oi.UNIT_PRICE) as AVG_SELLING_PRICE,
    p.COST,
    (AVG(oi.UNIT_PRICE) - p.COST) as PROFIT_MARGIN
FROM PRODUCTS p
JOIN CATEGORIES c ON p.CATEGORY_ID = c.CATEGORY_ID
LEFT JOIN ORDER_ITEMS oi ON p.PRODUCT_ID = oi.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.NAME, c.NAME, p.BRAND, p.COST;

-- Vue : Performance des magasins
CREATE VIEW V_STORE_PERFORMANCE AS
SELECT 
    s.STORE_ID,
    s.NAME as STORE_NAME,
    s.CITY,
    s.REGION,
    s.COUNTRY,
    COUNT(DISTINCT o.ORDER_ID) as TOTAL_ORDERS,
    COUNT(DISTINCT o.CUSTOMER_ID) as UNIQUE_CUSTOMERS,
    SUM(o.TOTAL_AMOUNT) as TOTAL_REVENUE,
    AVG(o.TOTAL_AMOUNT) as AVG_ORDER_VALUE,
    MAX(o.ORDER_DATE) as LAST_ORDER_DATE
FROM STORES s
LEFT JOIN ORDERS o ON s.STORE_ID = o.STORE_ID
GROUP BY s.STORE_ID, s.NAME, s.CITY, s.REGION, s.COUNTRY;

-- Vue : Analyse client
CREATE VIEW V_CUSTOMER_ANALYSIS AS
SELECT 
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME as CUSTOMER_NAME,
    c.EMAIL,
    c.CUSTOMER_SEGMENT,
    c.CITY,
    c.COUNTRY,
    COUNT(DISTINCT o.ORDER_ID) as TOTAL_ORDERS,
    SUM(o.TOTAL_AMOUNT) as TOTAL_SPENT,
    AVG(o.TOTAL_AMOUNT) as AVG_ORDER_VALUE,
    MIN(o.ORDER_DATE) as FIRST_ORDER_DATE,
    MAX(o.ORDER_DATE) as LAST_ORDER_DATE,
    DATEDIFF(day, MAX(o.ORDER_DATE), CURRENT_DATE()) as DAYS_SINCE_LAST_ORDER
FROM CUSTOMERS c
LEFT JOIN ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.EMAIL, 
         c.CUSTOMER_SEGMENT, c.CITY, c.COUNTRY;

-- =================================================================
-- INDEX POUR LES PERFORMANCES
-- =================================================================

-- Index sur les dates pour les requêtes temporelles
CREATE INDEX IDX_ORDERS_DATE ON ORDERS(ORDER_DATE);
CREATE INDEX IDX_ORDERS_CUSTOMER ON ORDERS(CUSTOMER_ID);
CREATE INDEX IDX_ORDERS_STORE ON ORDERS(STORE_ID);
CREATE INDEX IDX_ORDER_ITEMS_ORDER ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX IDX_ORDER_ITEMS_PRODUCT ON ORDER_ITEMS(PRODUCT_ID);
CREATE INDEX IDX_CUSTOMERS_SEGMENT ON CUSTOMERS(CUSTOMER_SEGMENT);
CREATE INDEX IDX_PRODUCTS_CATEGORY ON PRODUCTS(CATEGORY_ID);