-- =================================================================
-- SCRIPT 2: CRÉATION DES TABLES RETAIL DANS SNOWFLAKE
-- Optimisé pour les requêtes analytiques et les agents IA
-- =================================================================

USE WAREHOUSE RETAIL_WH;
USE DATABASE RETAIL_DEMO;
USE SCHEMA MAIN;

-- =================================================================
-- TABLES PRINCIPALES
-- =================================================================

-- Table des Catégories
CREATE OR REPLACE TABLE CATEGORIES (
    CATEGORY_ID INTEGER NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PARENT_CATEGORY_ID INTEGER,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    CONSTRAINT PK_CATEGORIES PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT FK_CATEGORIES_PARENT FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
) 
CLUSTER BY (CATEGORY_ID)
COMMENT = 'Table des catégories de produits avec hiérarchie';

-- Table des Produits
CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID INTEGER NOT NULL,
    NAME VARCHAR(200) NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,
    BRAND VARCHAR(100),
    PRICE NUMBER(10,2) NOT NULL,
    COST NUMBER(10,2) NOT NULL,
    STOCK_QUANTITY INTEGER DEFAULT 0,
    SUPPLIER VARCHAR(100),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
    CONSTRAINT CHK_PRICE_POSITIVE CHECK (PRICE > 0),
    CONSTRAINT CHK_COST_POSITIVE CHECK (COST > 0)
)
CLUSTER BY (CATEGORY_ID, BRAND)
COMMENT = 'Table des produits avec informations de prix et stock';

-- Table des Magasins
CREATE OR REPLACE TABLE STORES (
    STORE_ID INTEGER NOT NULL,
    NAME VARCHAR(150) NOT NULL,
    ADDRESS VARCHAR(300),
    CITY VARCHAR(100) NOT NULL,
    REGION VARCHAR(100),
    COUNTRY VARCHAR(100) NOT NULL DEFAULT 'France',
    POSTAL_CODE VARCHAR(20),
    MANAGER_NAME VARCHAR(100),
    OPENING_DATE DATE,
    STORE_TYPE VARCHAR(50) DEFAULT 'Standard',
    SURFACE_M2 INTEGER,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    CONSTRAINT PK_STORES PRIMARY KEY (STORE_ID),
    CONSTRAINT CHK_STORE_TYPE CHECK (STORE_TYPE IN ('Flagship', 'Standard', 'Outlet', 'Pop-up')),
    CONSTRAINT CHK_SURFACE_POSITIVE CHECK (SURFACE_M2 > 0)
)
CLUSTER BY (COUNTRY, REGION, CITY)
COMMENT = 'Table des magasins avec localisation géographique';

-- Table des Clients
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER NOT NULL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(20),
    ADDRESS VARCHAR(300),
    CITY VARCHAR(100),
    REGION VARCHAR(100),
    COUNTRY VARCHAR(100) NOT NULL DEFAULT 'France',
    POSTAL_CODE VARCHAR(20),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR(10),
    CUSTOMER_SEGMENT VARCHAR(50) DEFAULT 'Standard',
    REGISTRATION_DATE DATE NOT NULL,
    LAST_LOGIN_DATE TIMESTAMP_NTZ,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UK_CUSTOMERS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_CUSTOMER_SEGMENT CHECK (CUSTOMER_SEGMENT IN ('Premium', 'Standard', 'Bronze')),
    CONSTRAINT CHK_GENDER CHECK (GENDER IN ('M', 'F', 'Non-binaire'))
)
CLUSTER BY (CUSTOMER_SEGMENT, COUNTRY, REGISTRATION_DATE)
COMMENT = 'Table des clients avec segmentation et données démographiques';

-- Table des Commandes
CREATE OR REPLACE TABLE ORDERS (
    ORDER_ID INTEGER NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    STORE_ID INTEGER NOT NULL,
    ORDER_DATE TIMESTAMP_NTZ NOT NULL,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'Pending',
    TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
    DISCOUNT_AMOUNT NUMBER(10,2) DEFAULT 0,
    TAX_AMOUNT NUMBER(10,2) DEFAULT 0,
    PAYMENT_METHOD VARCHAR(50),
    SHIPPING_ADDRESS TEXT,
    DELIVERY_DATE TIMESTAMP_NTZ,
    NOTES TEXT,
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT FK_ORDERS_STORE FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID),
    CONSTRAINT CHK_ORDER_STATUS CHECK (STATUS IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled')),
    CONSTRAINT CHK_PAYMENT_METHOD CHECK (PAYMENT_METHOD IN ('Credit Card', 'Debit Card', 'Cash', 'PayPal', 'Apple Pay')),
    CONSTRAINT CHK_TOTAL_POSITIVE CHECK (TOTAL_AMOUNT >= 0)
)
CLUSTER BY (ORDER_DATE, STORE_ID)
COMMENT = 'Table des commandes avec statuts et informations de paiement';

-- Table des Lignes de Commande
CREATE OR REPLACE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID INTEGER NOT NULL,
    ORDER_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE NUMBER(10,2) NOT NULL,
    DISCOUNT_PERCENT NUMBER(5,2) DEFAULT 0,
    LINE_TOTAL NUMBER(12,2) AS (QUANTITY * UNIT_PRICE * (1 - DISCOUNT_PERCENT/100)),
    CREATED_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    
    CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT FK_ORDER_ITEMS_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    CONSTRAINT FK_ORDER_ITEMS_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT CHK_QUANTITY_POSITIVE CHECK (QUANTITY > 0),
    CONSTRAINT CHK_UNIT_PRICE_POSITIVE CHECK (UNIT_PRICE > 0),
    CONSTRAINT CHK_DISCOUNT_VALID CHECK (DISCOUNT_PERCENT >= 0 AND DISCOUNT_PERCENT <= 100)
)
CLUSTER BY (ORDER_ID, PRODUCT_ID)
COMMENT = 'Table des lignes de commande avec calcul automatique du total';

-- =================================================================
-- VUES ANALYTIQUES POUR LES AGENTS IA
-- =================================================================

USE SCHEMA ANALYTICS;

-- Vue : Analyse des Ventes par Produit
CREATE OR REPLACE VIEW V_PRODUCT_SALES AS
SELECT 
    p.PRODUCT_ID,
    p.NAME as PRODUCT_NAME,
    c.NAME as CATEGORY_NAME,
    p.BRAND,
    p.PRICE as CURRENT_PRICE,
    p.COST as PRODUCT_COST,
    COUNT(DISTINCT oi.ORDER_ID) as TOTAL_ORDERS,
    SUM(oi.QUANTITY) as TOTAL_QUANTITY_SOLD,
    SUM(oi.LINE_TOTAL) as TOTAL_REVENUE,
    AVG(oi.UNIT_PRICE) as AVG_SELLING_PRICE,
    SUM(oi.LINE_TOTAL) - (SUM(oi.QUANTITY) * p.COST) as TOTAL_PROFIT,
    ROUND((AVG(oi.UNIT_PRICE) - p.COST) / AVG(oi.UNIT_PRICE) * 100, 2) as PROFIT_MARGIN_PCT,
    COUNT(DISTINCT o.CUSTOMER_ID) as UNIQUE_CUSTOMERS,
    MIN(o.ORDER_DATE) as FIRST_SALE_DATE,
    MAX(o.ORDER_DATE) as LAST_SALE_DATE
FROM RETAIL_DEMO.MAIN.PRODUCTS p
JOIN RETAIL_DEMO.MAIN.CATEGORIES c ON p.CATEGORY_ID = c.CATEGORY_ID
LEFT JOIN RETAIL_DEMO.MAIN.ORDER_ITEMS oi ON p.PRODUCT_ID = oi.PRODUCT_ID
LEFT JOIN RETAIL_DEMO.MAIN.ORDERS o ON oi.ORDER_ID = o.ORDER_ID
WHERE o.STATUS != 'Cancelled'
GROUP BY p.PRODUCT_ID, p.NAME, c.NAME, p.BRAND, p.PRICE, p.COST
COMMENT = 'Vue analytique des ventes par produit avec métriques de performance';

-- Vue : Performance des Magasins
CREATE OR REPLACE VIEW V_STORE_PERFORMANCE AS
SELECT 
    s.STORE_ID,
    s.NAME as STORE_NAME,
    s.CITY,
    s.REGION,
    s.COUNTRY,
    s.STORE_TYPE,
    s.SURFACE_M2,
    COUNT(DISTINCT o.ORDER_ID) as TOTAL_ORDERS,
    COUNT(DISTINCT o.CUSTOMER_ID) as UNIQUE_CUSTOMERS,
    SUM(o.TOTAL_AMOUNT) as TOTAL_REVENUE,
    AVG(o.TOTAL_AMOUNT) as AVG_ORDER_VALUE,
    SUM(o.TOTAL_AMOUNT) / NULLIF(s.SURFACE_M2, 0) as REVENUE_PER_M2,
    COUNT(DISTINCT DATE(o.ORDER_DATE)) as ACTIVE_DAYS,
    SUM(CASE WHEN o.STATUS = 'Delivered' THEN 1 ELSE 0 END) as DELIVERED_ORDERS,
    ROUND(SUM(CASE WHEN o.STATUS = 'Delivered' THEN 1 ELSE 0 END) / COUNT(o.ORDER_ID) * 100, 2) as DELIVERY_SUCCESS_RATE,
    MIN(o.ORDER_DATE) as FIRST_ORDER_DATE,
    MAX(o.ORDER_DATE) as LAST_ORDER_DATE
FROM RETAIL_DEMO.MAIN.STORES s
LEFT JOIN RETAIL_DEMO.MAIN.ORDERS o ON s.STORE_ID = o.STORE_ID
GROUP BY s.STORE_ID, s.NAME, s.CITY, s.REGION, s.COUNTRY, s.STORE_TYPE, s.SURFACE_M2
COMMENT = 'Vue analytique de la performance des magasins';

-- Vue : Analyse Client Avancée
CREATE OR REPLACE VIEW V_CUSTOMER_ANALYSIS AS
SELECT 
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME as CUSTOMER_NAME,
    c.EMAIL,
    c.CUSTOMER_SEGMENT,
    c.CITY,
    c.REGION,
    c.COUNTRY,
    c.REGISTRATION_DATE,
    DATEDIFF(YEAR, c.DATE_OF_BIRTH, CURRENT_DATE()) as AGE,
    c.GENDER,
    c.IS_ACTIVE,
    COUNT(DISTINCT o.ORDER_ID) as TOTAL_ORDERS,
    SUM(o.TOTAL_AMOUNT) as TOTAL_SPENT,
    AVG(o.TOTAL_AMOUNT) as AVG_ORDER_VALUE,
    SUM(CASE WHEN o.ORDER_DATE >= DATEADD(MONTH, -12, CURRENT_DATE()) THEN o.TOTAL_AMOUNT ELSE 0 END) as SPEND_LAST_12M,
    SUM(CASE WHEN o.ORDER_DATE >= DATEADD(MONTH, -3, CURRENT_DATE()) THEN o.TOTAL_AMOUNT ELSE 0 END) as SPEND_LAST_3M,
    COUNT(DISTINCT oi.PRODUCT_ID) as UNIQUE_PRODUCTS_PURCHASED,
    COUNT(DISTINCT s.STORE_ID) as STORES_VISITED,
    MIN(o.ORDER_DATE) as FIRST_ORDER_DATE,
    MAX(o.ORDER_DATE) as LAST_ORDER_DATE,
    DATEDIFF(DAY, MAX(o.ORDER_DATE), CURRENT_DATE()) as DAYS_SINCE_LAST_ORDER,
    CASE 
        WHEN DATEDIFF(DAY, MAX(o.ORDER_DATE), CURRENT_DATE()) <= 30 THEN 'Active'
        WHEN DATEDIFF(DAY, MAX(o.ORDER_DATE), CURRENT_DATE()) <= 90 THEN 'At Risk'
        WHEN DATEDIFF(DAY, MAX(o.ORDER_DATE), CURRENT_DATE()) <= 365 THEN 'Dormant'
        ELSE 'Lost'
    END as LIFECYCLE_STATUS
FROM RETAIL_DEMO.MAIN.CUSTOMERS c
LEFT JOIN RETAIL_DEMO.MAIN.ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
LEFT JOIN RETAIL_DEMO.MAIN.ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
LEFT JOIN RETAIL_DEMO.MAIN.STORES s ON o.STORE_ID = s.STORE_ID
GROUP BY c.CUSTOMER_ID, c.FIRST_NAME, c.LAST_NAME, c.EMAIL, c.CUSTOMER_SEGMENT, 
         c.CITY, c.REGION, c.COUNTRY, c.REGISTRATION_DATE, c.DATE_OF_BIRTH, c.GENDER, c.IS_ACTIVE
COMMENT = 'Vue analytique complète des clients avec segmentation avancée';

-- Vue : Tendances Temporelles des Ventes  
CREATE OR REPLACE VIEW V_SALES_TRENDS AS
SELECT 
    DATE_TRUNC('MONTH', o.ORDER_DATE) as SALES_MONTH,
    DATE_TRUNC('WEEK', o.ORDER_DATE) as SALES_WEEK,
    DATE(o.ORDER_DATE) as SALES_DATE,
    EXTRACT(YEAR FROM o.ORDER_DATE) as SALES_YEAR,
    EXTRACT(MONTH FROM o.ORDER_DATE) as MONTH_NUM,
    EXTRACT(DAYOFWEEK FROM o.ORDER_DATE) as DAY_OF_WEEK,
    EXTRACT(HOUR FROM o.ORDER_DATE) as HOUR_OF_DAY,
    COUNT(DISTINCT o.ORDER_ID) as ORDERS_COUNT,
    COUNT(DISTINCT o.CUSTOMER_ID) as UNIQUE_CUSTOMERS,
    SUM(o.TOTAL_AMOUNT) as TOTAL_REVENUE,
    AVG(o.TOTAL_AMOUNT) as AVG_ORDER_VALUE,
    SUM(oi.QUANTITY) as TOTAL_ITEMS_SOLD,
    COUNT(DISTINCT oi.PRODUCT_ID) as UNIQUE_PRODUCTS_SOLD,
    COUNT(DISTINCT s.STORE_ID) as ACTIVE_STORES
FROM RETAIL_DEMO.MAIN.ORDERS o
JOIN RETAIL_DEMO.MAIN.ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
JOIN RETAIL_DEMO.MAIN.STORES s ON o.STORE_ID = s.STORE_ID
WHERE o.STATUS != 'Cancelled'
GROUP BY DATE_TRUNC('MONTH', o.ORDER_DATE), DATE_TRUNC('WEEK', o.ORDER_DATE), 
         DATE(o.ORDER_DATE), EXTRACT(YEAR FROM o.ORDER_DATE), EXTRACT(MONTH FROM o.ORDER_DATE),
         EXTRACT(DAYOFWEEK FROM o.ORDER_DATE), EXTRACT(HOUR FROM o.ORDER_DATE)
COMMENT = 'Vue des tendances temporelles pour l\'analyse saisonnière';

-- Vue : Top Performers (Résumé exécutif)
CREATE OR REPLACE VIEW V_TOP_PERFORMERS AS
SELECT 
    'Top Products' as METRIC_TYPE,
    p.NAME as ENTITY_NAME,
    c.NAME as CATEGORY,
    SUM(oi.LINE_TOTAL) as TOTAL_VALUE,
    COUNT(DISTINCT oi.ORDER_ID) as TRANSACTION_COUNT
FROM RETAIL_DEMO.MAIN.PRODUCTS p
JOIN RETAIL_DEMO.MAIN.CATEGORIES c ON p.CATEGORY_ID = c.CATEGORY_ID
JOIN RETAIL_DEMO.MAIN.ORDER_ITEMS oi ON p.PRODUCT_ID = oi.PRODUCT_ID
JOIN RETAIL_DEMO.MAIN.ORDERS o ON oi.ORDER_ID = o.ORDER_ID
WHERE o.STATUS != 'Cancelled'
GROUP BY p.PRODUCT_ID, p.NAME, c.NAME

UNION ALL

SELECT 
    'Top Customers' as METRIC_TYPE,
    cu.FIRST_NAME || ' ' || cu.LAST_NAME as ENTITY_NAME,
    cu.CUSTOMER_SEGMENT as CATEGORY,
    SUM(o.TOTAL_AMOUNT) as TOTAL_VALUE,
    COUNT(DISTINCT o.ORDER_ID) as TRANSACTION_COUNT
FROM RETAIL_DEMO.MAIN.CUSTOMERS cu
JOIN RETAIL_DEMO.MAIN.ORDERS o ON cu.CUSTOMER_ID = o.CUSTOMER_ID
WHERE o.STATUS != 'Cancelled'
GROUP BY cu.CUSTOMER_ID, cu.FIRST_NAME, cu.LAST_NAME, cu.CUSTOMER_SEGMENT

UNION ALL

SELECT 
    'Top Stores' as METRIC_TYPE,
    s.NAME as ENTITY_NAME,
    s.STORE_TYPE as CATEGORY,
    SUM(o.TOTAL_AMOUNT) as TOTAL_VALUE,
    COUNT(DISTINCT o.ORDER_ID) as TRANSACTION_COUNT
FROM RETAIL_DEMO.MAIN.STORES s
JOIN RETAIL_DEMO.MAIN.ORDERS o ON s.STORE_ID = o.STORE_ID
WHERE o.STATUS != 'Cancelled'
GROUP BY s.STORE_ID, s.NAME, s.STORE_TYPE
COMMENT = 'Vue consolidée des top performers par catégorie';

-- Messages de confirmation
SELECT 'Tables principales créées avec succès' AS STATUS;
SELECT 'Vues analytiques créées dans le schéma ANALYTICS' AS STATUS;
SELECT 'Contraintes et index configurés' AS STATUS;

-- Vérification des tables créées
SHOW TABLES IN SCHEMA RETAIL_DEMO.MAIN;
SHOW VIEWS IN SCHEMA RETAIL_DEMO.ANALYTICS;