"""
app.py -- Local demo application for the Foundry Retail Router agent.
Flask backend that consumes the orchestrator agent and exposes routing
(Snowflake detail vs Fabric aggregated) detected dynamically.

Launch:
    cd "...\demo_snow_agents\foundry"
    .venv\Scripts\python.exe app.py
    -> http://localhost:5000
"""
import json
from flask import Flask, request, jsonify, send_from_directory
from azure.identity import DefaultAzureCredential
from azure.ai.projects import AIProjectClient

ENDPOINT = (
    "https://aistudiodemo2519002580.services.ai.azure.com"
    "/api/projects/aistudiodemo2519002580-project"
)
AGENT_NAME = "Retail-Router-Azure-x-Snowflake"
MODEL = "gpt-4o"

app = Flask(__name__, static_folder="webui", static_url_path="")
_cred = DefaultAzureCredential()


def detect_routing(resp):
    """Determine the source(s) of the response.
    Priority is given to the SOURCE CITED by the agent in its final text
    ([Snowflake Data ...] / [Fabric Data ...]) -- that is the source
    it considers authoritative. The Cortex SQL is extracted from the mcp_call.
    """
    sql = None
    for item in resp.output:
        d = item.model_dump() if hasattr(item, "model_dump") else dict(item)
        if d.get("type") == "mcp_call":
            out = d.get("output", "") or ""
            if isinstance(out, str) and "SELECT" in out.upper() and sql is None:
                up = out.upper()
                i = up.find("SELECT")
                j = out.find("/* Generated by Cortex */")
                sql = out[i:(j if j > i else i + 600)].replace("\\n", "\n").replace("\\u003e", ">")

    txt = (resp.output_text or "")
    low = txt.lower()
    used = []
    # Based on explicit CITATION [Snowflake Data ...] / [Fabric Data ...]
    if "[snowflake data" in low:
        used.append("snowflake")
    if "[fabric data" in low:
        used.append("fabric")
    # Fallback on tool-calls if no explicit citation
    if not used:
        for item in resp.output:
            d = item.model_dump() if hasattr(item, "model_dump") else dict(item)
            t = d.get("type", "")
            if t == "mcp_call" and "snowflake" not in used:
                used.append("snowflake")
            if t == "fabric_dataagent_preview_call" and "fabric" not in used:
                used.append("fabric")
    return used, sql


@app.route("/")
def index():
    return send_from_directory("webui", "index.html")


@app.route("/api/chat", methods=["POST"])
def chat():
    body = request.json or {}
    question = (body.get("question", "") or "").strip()
    lang = (body.get("lang", "fr") or "fr").lower()
    if not question:
        return jsonify({"error": "empty question"}), 400
    directive = "Respond in French." if lang == "fr" else "Respond in English."
    prompt = f"{directive}\n\n{question}"
    try:
        with AIProjectClient(endpoint=ENDPOINT, credential=_cred) as pc:
            oai = pc.get_openai_client()
            try:
                resp = oai.responses.create(
                    model=MODEL,
                    input=prompt,
                    extra_body={"agent_reference": {"name": AGENT_NAME, "type": "agent_reference"}},
                )
                used, sql = detect_routing(resp)
                return jsonify({
                    "answer": resp.output_text,
                    "agents": used,
                    "sql": sql,
                })
            finally:
                oai.close()
    except Exception as e:
        return jsonify({"error": str(e)}), 500


if __name__ == "__main__":
    print("Retail Router demo UI -> http://localhost:5000")
    app.run(host="0.0.0.0", port=5000, debug=False)
